<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYoqa0yk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYoqa0yk/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYoqa0yk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYoqa0yk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYoqa0yk\appProdProjectContainer([
    'container.build_hash' => 'Yoqa0yk',
    'container.build_id' => '719b9e80',
    'container.build_time' => 1671050097,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYoqa0yk');
